-- Lua development is handled by AstroNvim v6 core:
--   - `folke/lazydev.nvim` is set up in `astronvim/plugins/lazydev.lua`
--   - it already wires the `lazydev` completion source into blink.cmp
--   - `vim.uv` typings come from `${3rd}/luv/library` (luvit-meta is no longer needed)
--
-- So the old v5 setup here (lazydev + luvit-meta + an nvim-cmp source) is redundant
-- in v6 and has been removed. blink.cmp is the default engine, not nvim-cmp.
--
-- If you ever need to add extra type libraries, extend lazydev's `library` here
-- (core uses `opts_extend = { "library" }`, so these are merged, not replaced):
--
-- ---@type LazySpec
-- return {
--   "folke/lazydev.nvim",
--   opts = {
--     library = {
--       -- { path = "path/to/your/types", words = { "SomeGlobal" } },
--     },
--   },
-- }

return {}
